fix(run-consul): use Azure provider retry_join for Consul 1.22.2
- Replace static IP retry_join with Azure cloud provider auto-discovery
- Remove deprecated 'ui: true' config key (removed in Consul 1.10+)
- Add --cloud-environment flag to support AzureUSGovernmentCloud
- Pass Azure credentials (subscription, tenant, client) to retry_join provider

diff --git a/modules/run-consul/run-consul b/modules/run-consul/run-consul
--- a/modules/run-consul/run-consul
+++ b/modules/run-consul/run-consul
@@ -1,6 +1,5 @@
 #!/bin/bash
 # This script is used to configure and run Consul on an Azure server.
-# Updated for Consul 1.22.2+ compatibility
 
 set -e
 
@@ -36,7 +35,6 @@ function print_usage {
   echo -e "                 \texception of cleanup_dead_servers. Default: 3"
   echo -e "  --user\t\tThe user to run Consul as. Optional. Default is to use the owner of --config-dir."
   echo -e "  --skip-consul-config\tIf this flag is set, don't generate a Consul configuration file. Optional. Default is false."
-  echo -e "  --scale-set-name\tThe name of the Azure Scale Set for retry_join with Azure provider. Optional."
   echo
   echo "Example:"
   echo
@@ -65,6 +63,7 @@ function log_error {
   log "ERROR" "$message"
 }
 
+# Based on code from: http://stackoverflow.com/a/16623897/483528
 function strip_prefix {
   local readonly str="$1"
   local readonly prefix="$2"
@@ -99,15 +98,81 @@ function get_instance_location {
   lookup_path_in_instance_metadata ".compute.location"
 }
 
+function get_instance_resource_group {
+  lookup_path_in_instance_metadata ".compute.resourceGroupName"
+}
+
 function get_instance_name {
   lookup_path_in_instance_metadata ".compute.name"
+}
+
+function get_other_scale_set_member_ip {
+    local readonly resource_group_name="$1"
+    local readonly scale_set_name="$2"
+    local readonly my_ip_address="$3"
+
+    ip_list=($(az vmss nic list --resource-group "$resource_group_name" --vmss-name "$scale_set_name" | jq '.[].ipConfigurations[].privateIpAddress'))
+    other_ip=""
+
+    for ip in ${ip_list[@]}; do
+        if [[ "$my_ip_address" != "$ip" ]]; then
+            other_ip="$ip"
+        fi
+    done
+
+    if [[ -z "$other_ip" ]]; then
+        log_warn "This Azure Instance does not appear to be part of a Scale Set, so cannot set retry_join peer."
+        echo ""
+    else
+        echo "$other_ip"
+    fi
+}
+
+function find_scale_set {
+  local readonly resource_group_name="$1"
+  local readonly instance_id="$2"
+
+  scale_set_name="unknown"
+  log_info "Finding the scale set Instance $instance_id belongs to"
+  scale_sets=($(az vmss list | jq -r .[]'.name'))
+  for scale_set in ${scale_sets[@]}; do
+    local instances=($(az vmss list-instances --resource-group $resource_group_name --name $scale_set | jq -r .[]'.vmId'))
+    for instance in ${instances[@]}; do
+        if [[ "$instance"==$instance_id ]]; then
+            scale_set_name=$scale_set
+        fi
+    done
+  done
+  echo "$scale_set_name"
+}
+
+function get_scale_set_size {
+  local readonly resource_group_name="$1"
+  local readonly scale_set_name="$2"
+  local vmss_json=""
+
+  log_info "Looking up the size of the Scale Set $scale_set_name in $resource_group_name"
+  vmss_json=$(az vmss list-instances --resource-group $resource_group_name --name $scale_set_name)
+  echo "$vmss_json" | jq '. | length'
+}
+
+function get_cluster_size {
+  local readonly resource_group_name="$1"
+  local readonly scale_set_name="$2"
+
+  if [[ "$scale_set_name" = "unknown" ]]; then
+    log_warn "This Azure Instance does not appear to be part of a Scale Set, so cannot determine cluster size. Setting cluster size to 1."
+    echo 1
+  else
+    get_scale_set_size "$resource_group_name" "$scale_set_name"
+  fi
 }
 
 function assert_is_installed {
   local readonly name="$1"
 
   if [[ ! $(command -v ${name}) ]]; then
-    log_error "The binary '$name' is required by this script but is not installed or is not in the system's PATH."
+    log_error "The binary '$name' is required by this script but is not installed or in the system's PATH."
     exit 1
   fi
 }
@@ -123,8 +188,8 @@ function generate_consul_config {
   local readonly secret_access_key="$8"
   local readonly scale_set_name="$9"
   local readonly cloud_environment="${10}"
-  
-  local config_path="$config_dir/$CONSUL_CONFIG_FILE"
+  local readonly config_path="$config_dir/$CONSUL_CONFIG_FILE"
+
   local instance_ip_address=""
   local instance_id=""
   local instance_location=""
@@ -133,16 +198,15 @@ function generate_consul_config {
   instance_id=$(get_instance_id)
   instance_location=$(get_instance_location)
 
+  local azure_env="AzurePublicCloud"
+  if [[ "$cloud_environment" == "USGovernment" ]] || [[ "$cloud_environment" == "AzureUSGovernmentCloud" ]]; then
+    azure_env="AzureUSGovernmentCloud"
+  fi
+
   local retry_join_json=""
-  
-  # Build retry_join with Azure provider for auto-join (Consul 1.10+)
-  if [[ -n "$scale_set_name" ]]; then
-    log_info "Configuring Azure provider retry_join with scale set: $scale_set_name"
-    local azure_env="AzurePublicCloud"
-    if [[ "$cloud_environment" == "USGovernment" ]] || [[ "$cloud_environment" == "AzureUSGovernmentCloud" ]]; then
-      azure_env="AzureUSGovernmentCloud"
-    fi
-    
+  if [[ -z "$scale_set_name" ]]; then
+    log_warn "Scale set name not provided. retry_join will not be configured."
+  else
     retry_join_json=$(cat <<EOF
 "retry_join": [
   {
@@ -158,13 +222,15 @@ function generate_consul_config {
 ],
 EOF
 )
-  else
-    log_warn "Scale set name not provided. retry_join will not be configured."
   fi
 
   local bootstrap_expect=""
   if [[ "$server" == "true" ]]; then
-    bootstrap_expect="\"bootstrap_expect\": 3,"
+    local cluster_size=""
+
+    cluster_size=$(get_cluster_size "$instance_resource_group" "$scale_set_name")
+
+    bootstrap_expect="\"bootstrap_expect\": $cluster_size,"
   fi
 
   log_info "Creating default Consul config file in $config_path"
@@ -182,7 +248,6 @@ EOF
 }
 EOF
   chown "$user:$user" "$config_path"
-  log_info "Consul config generated successfully"
 }
 
 function generate_supervisor_config {
@@ -207,6 +272,18 @@ user=$consul_user
 EOF
 }
 
+function start_consul {
+  log_info "Reloading Supervisor config and starting Consul"
+  supervisorctl reread
+  supervisorctl update
+}
+
+# Based on: http://unix.stackexchange.com/a/7732/215969
+function get_owner_of_path {
+  local readonly path="$1"
+  ls -ld "$path" | awk '{print $3}'
+}
+
 function do_azure_login {
   local tenant_id="$1"
   local client_id="$2"
@@ -224,15 +301,16 @@ function run {
   local log_dir=""
   local bin_dir=""
   local user=""
-  local raft_protocol="$DEFAULT_RAFT_PROTOCOL"
-  local skip_consul_config="false"
+  local cloud_environment="AzurePublicCloud"
   local subscription_id=""
   local tenant_id=""
   local client_id=""
   local secret_access_key=""
-  local cloud_environment="AzurePublicCloud"
+  local skip_consul_config="false"
+  local raft_protocol="$DEFAULT_RAFT_PROTOCOL"
+  local all_args=()
 
-  while [[ $# -gt 0 ]]; do
+  while [[ $# > 0 ]]; do
     local key="$1"
 
     case "$key" in
@@ -242,50 +320,61 @@ function run {
       --client)
         client="true"
         ;;
+      --scale-set-name)
+        assert_not_empty "$key" "$2"
+        scale_set_name="$2"
+        shift
+        ;;
+      --raft-protocol)
+        assert_not_empty "$key" "$2"
+        raft_protocol="$2"
+        shift
+        ;;
       --config-dir)
+        assert_not_empty "$key" "$2"
         config_dir="$2"
         shift
         ;;
       --data-dir)
+        assert_not_empty "$key" "$2"
         data_dir="$2"
         shift
         ;;
       --log-dir)
+        assert_not_empty "$key" "$2"
         log_dir="$2"
         shift
         ;;
       --bin-dir)
+        assert_not_empty "$key" "$2"
         bin_dir="$2"
         shift
         ;;
       --user)
+        assert_not_empty "$key" "$2"
         user="$2"
-        shift
-        ;;
-      --raft-protocol)
-        raft_protocol="$2"
         shift
         ;;
       --skip-consul-config)
         skip_consul_config="true"
         ;;
-      --scale-set-name)
-        scale_set_name="$2"
-        shift
-        ;;
       --subscription-id)
+        assert_not_empty "$key" "$2"
         subscription_id="$2"
         shift
         ;;
       --tenant-id)
+        assert_not_empty "$key" "$2"
         tenant_id="$2"
         shift
         ;;
       --client-id)
+        assert_not_empty "$key" "$2"
         client_id="$2"
         shift
         ;;
       --secret-access-key)
+        assert_not_empty "$key" "$2"
         secret_access_key="$2"
         shift
         ;;
@@ -307,42 +396,73 @@ function run {
     shift
   done
 
-  assert_is_installed "consul"
-  assert_is_installed "supervisorctl"
-  assert_is_installed "jq"
-  assert_not_empty "--config-dir" "$config_dir"
-  assert_not_empty "--data-dir" "$data_dir"
-  assert_not_empty "--log-dir" "$log_dir"
-  assert_not_empty "--bin-dir" "$bin_dir"
+  assert_not_empty "subscription-id" "$subscription_id"
+  assert_not_empty "tenant-id" "$tenant_id"
+  assert_not_empty "client-id" "$client_id"
+  assert_not_empty "secret-access-key" "$secret_access_key"
 
-  if [[ "$server" == "true" ]] && [[ "$client" == "true" ]]; then
-    log_error "Exactly one of --server or --client must be set"
+  do_azure_login "$tenant_id" "$client_id" "$secret_access_key"
+
+  if [[ ("$server" == "true" && "$client" == "true") || ("$server" == "false" && "$client" == "false") ]]; then
+    log_error "Exactly one of --server or --client must be set."
     exit 1
   fi
 
-  if [[ "$server" == "false" ]] && [[ "$client" == "false" ]]; then
-    log_error "Exactly one of --server or --client must be set"
+  if [[ "$client" == "true" && -z "$scale_set_name" ]]; then
+    log_error "--scale-set-name must be set if --client is set."
     exit 1
+  fi
+
+  assert_is_installed "supervisorctl"
+  assert_is_installed "az"
+  assert_is_installed "curl"
+  assert_is_installed "jq"
+
+  if [[ -z "$config_dir" ]]; then
+    config_dir=$(cd "$SCRIPT_DIR/../config" && pwd)
+  fi
+
+  if [[ -z "$data_dir" ]]; then
+    data_dir=$(cd "$SCRIPT_DIR/../data" && pwd)
+  fi
+
+  if [[ -z "$log_dir" ]]; then
+    log_dir=$(cd "$SCRIPT_DIR/../log" && pwd)
+  fi
+
+  if [[ -z "$bin_dir" ]]; then
+    bin_dir=$(cd "$SCRIPT_DIR/../bin" && pwd)
   fi
 
   if [[ -z "$user" ]]; then
     user=$(get_owner_of_path "$config_dir")
   fi
 
-  # Create config/data/log directories if they don't exist
-  mkdir -p "$config_dir" "$data_dir" "$log_dir"
-  chown "$user:$user" "$config_dir" "$data_dir" "$log_dir"
+  if [[ "$skip_consul_config" == "true" ]]; then
+    log_info "The --skip-consul-config flag is set, so will not generate a default Consul config file."
+  else
+    instance_id=$(get_instance_id)
+    resource_group=$(get_instance_resource_group)
 
-  if [[ "$skip_consul_config" == "false" ]]; then
-    generate_consul_config "$server" "$raft_protocol" "$config_dir" "$user" "$subscription_id" "$tenant_id" "$client_id" "$secret_access_key" "$scale_set_name" "$cloud_environment"
+    if [[ -z "$scale_set_name" ]]; then
+      scale_set_name=$(find_scale_set "$resource_group" "$instance_id")
+    fi
+
+    generate_consul_config \
+        "$server" \
+        "$raft_protocol" \
+        "$config_dir" \
+        "$user" \
+        "$subscription_id" \
+        "$tenant_id" \
+        "$client_id" \
+        "$secret_access_key" \
+        "$scale_set_name" \
+        "$cloud_environment"
   fi
 
   generate_supervisor_config "$SUPERVISOR_CONFIG_PATH" "$config_dir" "$data_dir" "$log_dir" "$bin_dir" "$user"
-}
-
-function get_owner_of_path {
-  local readonly path="$1"
-  ls -ld "$path" | awk '{print $3}'
+  start_consul
 }
 
 run "$@"
